---
- name: Diretorio local Vim
  file:
    path: "~/.vim/{{ item }}"
    state: directory
    mode: 0755
  loop:
    - autoload
    - bundle
  become_user: "{{ user_username }}"

- name: Instala Vim Pathogen Plugin Manager
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim
  become_user: "{{ user_username }}"

- name: Instala plugins para o vim
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop:
    - repo: https://github.com/vim-airline/vim-airline.git
      dest: ~/.vim/bundle/vim-airline
    - repo: https://github.com/vim-airline/vim-airline-themes.git
      dest: ~/.vim/bundle/vim-airline-themes
    - repo: https://github.com/jmcantrell/vim-virtualenv.git
      dest: ~/.vim/bundle/vim-virtualenv
    - repo: https://github.com/tpope/vim-fugitive.git
      dest: ~/.vim/bundle/vim-fugitive
  become_user: "{{ user_username }}"

- name: Configura o Vim
  copy:
    src: vimrc
    dest: ~/.vimrc
    owner: "{{ user_username }}"
    mode: 0644
  become_user: "{{ user_username }}"

- name: Configura o gitignore
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    owner: "{{ user_username }}"
    mode: 0644
  become_user: "{{ user_username }}"

- name: Configura o Bash
  blockinfile:
    path: ~/.bashrc
    insertafter: EOF
    block: |
      export EDITOR=`which vim`
      export COR='--color=auto'
      eval "`dircolors`"

      alias ls='ls $COR'
      alias l='ls $COR -lahF'

      alias grep='grep $COR'
      alias egrep='egrep $COR'
      alias fgrep='fgrep $COR'

      function parse_git_dirty {
        GSTATUS=$(git status 2> /dev/null | tail -n1) ; [[ $GSTATUS != "nothing to commit, working directory clean" ]] && [[ $GSTATUS != "nothing to commit, working tree clean" ]] && echo "*"
      }

      function parse_git_branch {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/(\1$(parse_git_dirty))/"
      }

      PS1='\[\e[01;32m\][\[\e[0m\]\[\e[01;37m\]\u@\h:\[\e[0m\]\[\e[0;33m\]\w\[\e[0m\]\[\e[00;37m\] \[\e[01;31m\]$(parse_git_branch "(%s)" )\[\e[00m\]\[\e[01;32m\]]\[\e[0m\]\[\e[01;37m\]\$\[\e[0m\] '
  become_user: "{{ user_username }}"

- name: Configura dark mode no Gnome
  blockinfile:
    path: ~/.config/gtk-3.0/settings.ini
    insertafter: EOF
    state: present
    block: |
      [Settings]
      gtk-application-prefer-dark-theme=1
  become_user: "{{ user_username }}"

- name: Configura Gnome
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - key: "/org/gnome/nautilus/icon-view/default-zoom-level"
      value: "'small'"
    - key: "/org/gnome/desktop/interface/show-battery-percentage"
      value: "true"
    - key: "/org/gnome/desktop/interface/clock-format"
      value: "'24h'"
    - key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"
    - key: "/org/gnome/desktop/interface/clock-show-seconds"
      value: "false"
    - key: "/org/gnome/desktop/privacy/old-files-age"
      value: "uint32 3"
    - key: "/org/gnome/desktop/privacy/remove-old-temp-files"
      value: "true"
    - key: "/org/gnome/desktop/privacy/remove-old-trash-files"
      value: "true"
    - key: "/org/gnome/desktop/sound/input-feedback-sounds"
      value: "false"
