---
- name: vim plugins dir
  file:
    path: "~/.vim/{{ item }}"
    state: directory
    mode: 0755
  loop:
    - autoload
    - bundle
  become_user: "{{ user_username }}"

- name: vim pathogen plugin
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim
  become_user: "{{ user_username }}"

- name: install vim-airline plugin
  git:
    repo: https://github.com/vim-airline/vim-airline.git
    dest: ~/.vim/bundle/vim-airline
  become_user: "{{ user_username }}"

- name: install vim-airline-themes plugin
  git:
    repo: https://github.com/vim-airline/vim-airline-themes.git
    dest: ~/.vim/bundle/vim-airline-themes
  become_user: "{{ user_username }}"

- name: install vim-virtualenv plugin
  git:
    repo: https://github.com/jmcantrell/vim-virtualenv.git
    dest: ~/.vim/bundle/vim-virtualenv
  become_user: "{{ user_username }}"

- name: install vim-fugitive plugin
  git:
    repo: https://github.com/tpope/vim-fugitive.git
    dest: ~/.vim/bundle/vim-fugitive
  become_user: "{{ user_username }}"

- name: vim config
  copy:
    src: vimrc
    dest: ~/.vimrc
    owner: "{{ user_username }}"
    mode: 0644
  become_user: "{{ user_username }}"

- name: git config
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    owner: "{{ user_username }}"
    mode: 0644
  become_user: "{{ user_username }}"

- name: bash
  blockinfile:
    path: ~/.bashrc
    insertafter: EOF
    content: |
      export EDITOR=`which vim`
      export COR='--color=auto'
      eval "`dircolors`"

      alias ls='ls $COR'
      alias l='ls $COR -lahF'

      alias grep='grep $COR'
      alias egrep='egrep $COR'
      alias fgrep='fgrep $COR'

      function parse_git_dirty {
        GSTATUS=$(git status 2> /dev/null | tail -n1) ; [[ $GSTATUS != "nothing to commit, working directory clean" ]] && [[ $GSTATUS != "nothing to commit, working tree clean" ]] && echo "*"
      }

      function parse_git_branch {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/(\1$(parse_git_dirty))/"
      }

      PS1='\[\e[01;32m\][\[\e[0m\]\[\e[01;37m\]\u@\h:\[\e[0m\]\[\e[0;33m\]\w\[\e[0m\]\[\e[00;37m\] \[\e[01;31m\]$(parse_git_branch "(%s)" )\[\e[00m\]\[\e[01;32m\]]\[\e[0m\]\[\e[01;37m\]\$\[\e[0m\] '
  become_user: "{{ user_username }}"
