---
- name: Configura repositorio oficial
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root
    group: root
  register: sourceslist

- block:
    - name: Instala a chave do repositorio OpenVPN
      apt_key:
        url: https://swupdate.openvpn.net/repos/repo-public.gpg

    - name: Configura repositorio OpenVPN
      apt_repository:
        repo: deb http://build.openvpn.net/debian/openvpn/stable {{ ansible_distribution_release|lower }} main
        filename: openvpn
      register: openvpnlist
  when: ansible_distribution == "Debian"

- name: Habilita PPA do Git
  apt_repository:
    repo: ppa:git-core/ppa
    state: present
  when: ansible_distribution == "Ubuntu"
  register: gitlist
  tags:
    - pkg:git
    - pkg:git:ppa
    - pkg:dev

- name: Atualiza cache do APT
  apt:
    update_cache: yes
  when: sourceslist.changed or openvpnlist.changed or gitlist.changed
  tags: pkg:update

- name: Instala pacotes básicos
  apt:
    name: "{{ pkg_base }}"
    state: present
    install_recommends: no
  tags: pkg:base

- name: Instala pacotes relacionados ao Git
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop:
    - git
    - git-doc
    - git-gui
    - gitk
    - tig
  tags:
    - pkg:git
    - pkg:dev

- name: Instala ferramentas de desenvolvimento
  apt:
    name: "{{ pkg_dev }}"
    state: present
    install_recommends: no
  tags: pkg:dev

- name: Instala ferramentas de administração de sistema
  apt:
    name: "{{ pkg_sysadmin }}"
    state: present
    install_recommends: no
  tags: pkg:sysadmin

- name: Instala ferramentas de gráficos e multimídia
  apt:
    name: "{{ pkg_media }}"
    state: present
    install_recommends: no
  tags: pkg:media

- name: Instala pacotes utilitários
  apt:
    name: "{{ pkg_misc }}"
    state: present
    install_recommends: no
  tags:
    - pkg:misc
    - pkg:utils

- name: Instala pacotes backports quando for Debian
  apt:
    name: "{{ pkg_backports }}"
    state: present
    install_recommends: no
    default_release: "{{ ansible_distribution_release|lower }}-backports"
  when: ansible_distribution == "Debian"
  tags:
    - pkg:backports

- name: Instala pacotes backports quando for Ubuntu
  apt:
    name: "{{ pkg_backports }}"
    state: present
    install_recommends: no
  when: ansible_distribution == "Ubuntu"
  tags:
    - pkg:backports

- name: Remove pacotes selecionados
  apt:
    name: "{{ pkg_purge }}"
    state: absent
    purge: yes
  tags: pkg:purge

- name: Instala pacotes extras
  apt:
    name: "{{ pkg_extra }}"
    state: present
    install_recommends: no
  tags: pkg:extra
