---
- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart NetworkManager
  service: name=NetworkManager state=restarted
  
- name: restart ufw
  service: name=ufw state=restarted