---
- name: Verifica se VSCode está instalado
  shell: dpkg-query --show code || true
  register: code_check
  changed_when: false

# Tarefas de instalação
- include: install-deb.yml
  when: "'no packages found matching' in code_check.stderr"
