---
- name: Verifica se rclone {{ rclone_version }} está instalado
  shell: rclone version || true
  register: rclone_check
  changed_when: false

- name: Baixa e extrai arquivo zip
  unarchive:
    remote_src: true
    src: "{{ rclone_dl_url }}"
    dest: /tmp
  when: >
    rclone_check.stdout_lines | length == 0
    or rclone_version not in rclone_check.stdout_lines[0]

- name: Instala binário
  copy:
    remote_src: true
    src: /tmp/rclone-v{{ rclone_version }}-linux-amd64/rclone
    dest: "{{ rclone_path }}"
    owner: root
    group: root
    mode: 0755
  when: >
    rclone_check.stdout_lines | length == 0
    or rclone_version not in rclone_check.stdout_lines[0]

- name: Configura Bash completion
  command: >
    rclone genautocomplete bash /etc/bash_completion.d/rclone
  when: >
    rclone_check.stdout_lines | length == 0
    or rclone_version not in rclone_check.stdout_lines[0]
  tags: rclone:completion
