---
- name: gnome config - show battery percentage
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"
    state: present
  become_user: "{{ user_username }}"
    
- name: gnome config - icon small
  dconf:
    key: "/org/gnome/nautilus/icon-view/default-zoom-level"
    value: "'small'"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - clock format
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - clock date
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - clock seconds
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "false"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - lock keys
  dconf:
    key: "/org/gnome/shell/extensions/lockkeys/style"
    value: "'show-hide'"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - top icon - size
  dconf:
    key: "/org/gnome/shell/extensions/topicons/icon-size"
    value: "18"
    state: present
  become_user: "{{ user_username }}"
  
- name: gnome config - top icon - spacing
  dconf:
    key: "/org/gnome/shell/extensions/topicons/icon-spacing"
    value: "10"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - top icon - opacity
  dconf:
    key: "/org/gnome/shell/extensions/topicons/icon-opacity"
    value: "120"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - impatience
  dconf:
    key: "/org/gnome/shell/extensions/net/gfxmonk/impatience/speed-factor"
    value: "0.70"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - old files age
  dconf:
    key: "/org/gnome/desktop/privacy/old-files-age"
    value: "uint32 3"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - remove-old-temp-files
  dconf:
    key: "/org/gnome/desktop/privacy/remove-old-temp-files"
    value: "true"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - remove-old-trash-files
  dconf:
    key: "/org/gnome/desktop/privacy/remove-old-trash-files"
    value: "true"
    state: present
  become_user: "{{ user_username }}"

- name: gnome config - feedback sounds
  dconf:
    key: "/org/gnome/desktop/sound/input-feedback-sounds"
    value: "false"
    state: present
  become_user: "{{ user_username }}"

- name: global dark theme
  blockinfile:
    path: ~/.config/gtk-3.0/settings.ini
    insertafter: EOF
    state: present
    block: |
      [Settings]
      gtk-application-prefer-dark-theme=1
  become_user: "{{ user_username }}"

