let g:skip_defaults_vim = 0

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

set smartcase
set showmatch
set showcmd

" Desabilita backups
set nobackup
set noswapfile
set nowritebackup

" Busca
set ignorecase
set hlsearch
set incsearch

" Codificação
set encoding=utf-8
set fileencoding=utf-8

" Visual (cores, tema etc)
filetype on
filetype plugin off
syntax on
colorscheme elflord
set background=dark

" Tabs e espaços
set expandtab
set nostartofline
set shiftwidth=4
set tabstop=4

" Cursor e colunas
set cursorline
"set cursorcolumn
hi CursorLine term=bold cterm=bold guibg=Grey40

" Sintaxe de arquivos
au BufNewFile,BufRead composer.lock set filetype=json
au BufNewFile,BufRead docker-compose*.yml set filetype=yaml
au BufNewFile,BufRead Jenkinsfile set filetype=groovy
au BufNewFile,BufRead Vagrantfile set filetype=ruby
au BufNewFile,BufRead *.textile set filetype=redminewiki
au BufNewFile,BufRead *.tfstate set filetype=json

" Pathogen
if filereadable(expand($HOME . "/.vim/autoload/pathogen.vim"))
    execute pathogen#infect()
endif

" Needs by Airline
set laststatus=2
set t_Co=256
set noshowmode
let g:airline_powerline_fonts = 1
