---
# Refs:
#  - https://www.vagrantup.com/downloads.html
#  - https://github.com/cogitatio/vagrant-hostsupdater#installation

vagrant_version: 2.2.5

# Exemplo: plugin1,plugin2,plugin3
vagrant_plugins: vagrant-digitalocean,vagrant-hostsupdater

vagrant_update_plugins: yes
