---
- name: Instala chave do reposit칩rio
  apt_key:
    url: "{{ vbox_repo_key_url }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/virtualbox.gpg
  tags:
    - vbox:repo
    - vbox:install

- name: Configura reposit칩rio
  apt_repository:
    repo: "{{ vbox_repo_line }}"
    filename: "{{ vbox_repo_file }}"
    state: present
    update_cache: yes
  tags:
    - vbox:repo
    - vbox:install

- name: Instala VirtualBox
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop:
    - virtualbox-{{ vbox_version_major }}
    - libsdl-ttf2.0-0
  tags: vbox:install

- name: Adiciona usu치rio ao grupo 'vboxusers'
  user:
    name: "{{ vbox_user | default(lookup('env', 'USER')) }}"
    groups: vboxusers
    append: yes
  tags: vbox:install

- name: Verifica se Extension Pack est치 instalado
  shell: vboxmanage list extpacks | grep '^Version:.*{{ vbox_extpack_version }}$'
  register: vbox_check_extpack
  failed_when: vbox_check_extpack.rc > 1
  changed_when: false
  tags: vbox:extpack

- name: Baixa Extension Pack
  get_url:
    url: "{{ vbox_extpack_url }}"
    dest: "{{ vbox_extpack_dl_file }}"
  when: vbox_check_extpack.rc == 1
  tags: vbox:extpack

- name: Instala Extension Pack
  shell: echo yes | vboxmanage extpack install --replace {{ vbox_extpack_dl_file }}
  when: vbox_check_extpack.rc == 1
  tags: vbox:extpack
