let g:skip_defaults_vim = 0

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set smartcase           " Do smart case matching
set showmatch
set showcmd

set tabstop=4
set hlsearch
set cursorline
"set cursorcolumn
hi CursorLine term=bold cterm=bold guibg=Grey40

"Needs by Pathogen
execute pathogen#infect()

"Needs by Airline
set laststatus=2
set t_Co=256
set noshowmode
let g:airline_powerline_fonts = 1
