---
- name: Dependencias para EHfive / pulseaudio-modules-bt
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  loop:
    - libpulse-dev
    - cmake
    - libdbus-1-dev
    - libsbc-dev
    - libbluetooth-dev
    - libtool
    - libpulse-dev

- name: Instala EHfive / pulseaudio-modules-bt
  shell: |
    git clone https://github.com/EHfive/pulseaudio-modules-bt.git
    cd pulseaudio-modules-bt
    git submodule update --init
    git -C pa/ checkout v`pkg-config libpulse --modversion|sed 's/[^0-9.]*\([0-9.]*\).*/\1/'`
    mkdir build && cd build
    cmake ..
    make
    make install
