---
- name: Verifica se Skype está instalado
  shell: dpkg-query --show skypeforlinux || true
  register: skype_check
  changed_when: false

# Tarefas de instalação
- include: install-deb.yml
  when: "'no packages found matching' in skype_check.stderr"
