---  
dependencies:
  - role: ansible-gnome_shell
    vars:
        gnome_extension_path: "~/.local/share/gnome-shell/extensions"
        gnome_extension_owner: "{{ user_username }}"
        gnome_shell_extensions: [4, 1031, 759, 277, 36, 48]